ALTER TABLE MEDICO

RENAME COLUMN id TO ID,
RENAME COLUMN nome TO NOME,
RENAME COLUMN email TO EMAIL,
RENAME COLUMN crm TO CRM,
RENAME COLUMN especialidade TO ESPECIALIDADE,
RENAME COLUMN logradouro TO LOGRADOURO,
RENAME COLUMN bairro TO BAIRRO,
RENAME COLUMN cep TO CEP,
RENAME COLUMN complemento TO COMPLEMENTO,
RENAME COLUMN numero TO NUMERO,
RENAME COLUMN uf TO UF,
RENAME COLUMN cidade TO CIDADE,
RENAME COLUMN telefone TO TELEFONE,
RENAME COLUMN ativo TO ATIVO
