alter table CONSULTA
CHANGE dataDaConsulta DATA DATE NOT NULL,
CHANGE horaDaConsulta HORA TIME NOT NULL,
RENAME COLUMN id TO ID,
RENAME COLUMN id_paciente TO ID_PACIENTE,
RENAME COLUMN id_medico TO ID_MEDICO